# Generated by Django 3.0.5 on 2020-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200507_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='verifytime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
