# Generated by Django 3.0.5 on 2020-05-08 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200507_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='jmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experimentnum', models.CharField(max_length=32)),
                ('low', models.FloatField()),
                ('median', models.FloatField()),
                ('high', models.FloatField()),
                ('jmd2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportInfo')),
            ],
        ),
    ]
