# Generated by Django 3.0.5 on 2020-05-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_jmd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmd',
            old_name='jmd2',
            new_name='reportinfo',
        ),
    ]
