# Generated by Django 3.0.5 on 2020-05-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200508_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jmd',
            new_name='PNjmd',
        ),
    ]
