# Generated by Django 3.0.5 on 2020-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20200511_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnjmd',
            name='norm',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
