# Generated by Django 3.0.5 on 2020-05-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_pt'),
    ]

    operations = [
        migrations.CreateModel(
            name='endreportjmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=200)),
                ('second', models.CharField(max_length=200)),
                ('last', models.CharField(max_length=200)),
            ],
        ),
    ]
