# Generated by Django 3.0.5 on 2020-05-26 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_endreportjmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.main')),
            ],
        ),
    ]
