# Generated by Django 3.0.5 on 2020-05-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_main_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='jmdbackstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=32, verbose_name='项目')),
                ('number', models.FloatField()),
                ('CV', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='endreportjmd',
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': '描述性信息输入端口', 'verbose_name_plural': '描述性信息输入端口'},
        ),
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': '描述性信息', 'verbose_name_plural': '描述性信息'},
        ),
        migrations.AlterField(
            model_name='main',
            name='item',
            field=models.CharField(max_length=32, verbose_name='指标'),
        ),
        migrations.AlterField(
            model_name='main',
            name='project',
            field=models.CharField(max_length=32, verbose_name='项目'),
        ),
    ]
