# Generated by Django 3.0.5 on 2020-05-27 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20200527_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=32, verbose_name='项目')),
                ('number', models.FloatField(verbose_name='需要提交的最小样本数')),
                ('criticalnumber', models.FloatField(verbose_name='判断标准')),
            ],
            options={
                'verbose_name': 'PT信息输入端口',
                'verbose_name_plural': 'PT信息输入端口',
            },
        ),
        migrations.AlterModelOptions(
            name='jmdbackstage',
            options={'verbose_name': '精密度信息输入端口', 'verbose_name_plural': '精密度信息输入端口'},
        ),
        migrations.AlterField(
            model_name='jmdbackstage',
            name='CV',
            field=models.FloatField(verbose_name='判断标准'),
        ),
        migrations.AlterField(
            model_name='jmdbackstage',
            name='number',
            field=models.FloatField(verbose_name='需要提交的最小样本数'),
        ),
        migrations.CreateModel(
            name='PTbackstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTnorm', models.CharField(max_length=32, verbose_name='指标')),
                ('PTmain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PTmain')),
            ],
            options={
                'verbose_name': '指标',
                'verbose_name_plural': '指标',
            },
        ),
    ]
