# Generated by Django 3.0.5 on 2020-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_ptbackstage_ptnormtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptbackstage',
            name='PTnormtargetunit',
            field=models.CharField(default='', max_length=20, verbose_name='单位1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTreceptablehigh',
            field=models.FloatField(default=1, verbose_name='大于临界值的可接受标准'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTreceptablehighunit',
            field=models.CharField(default='', max_length=20, verbose_name='单位3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTreceptablelow',
            field=models.FloatField(default=1, verbose_name='小于临界值的可接受标准'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTreceptablelowunit',
            field=models.CharField(default='', max_length=20, verbose_name='单位2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ptbackstage',
            name='PTnorm',
            field=models.CharField(max_length=20, verbose_name='指标'),
        ),
        migrations.AlterField(
            model_name='ptbackstage',
            name='PTnormtarget',
            field=models.FloatField(verbose_name='临界值'),
        ),
    ]
