# Generated by Django 3.0.5 on 2020-05-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20200527_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptbackstage',
            options={'verbose_name': '对应指标相关信息', 'verbose_name_plural': '对应指标相关信息'},
        ),
        migrations.RemoveField(
            model_name='ptbackstage',
            name='PTnormtarget',
        ),
        migrations.RemoveField(
            model_name='ptbackstage',
            name='PTnormtargetunit',
        ),
        migrations.RemoveField(
            model_name='ptbackstage',
            name='PTreceptablehigh',
        ),
        migrations.RemoveField(
            model_name='ptbackstage',
            name='PTreceptablehighunit',
        ),
        migrations.RemoveField(
            model_name='ptbackstage',
            name='PTreceptablelow',
        ),
        migrations.RemoveField(
            model_name='ptbackstage',
            name='PTreceptablelowunit',
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTnormrange1',
            field=models.FloatField(default=1, verbose_name='判断标准一适用范围(<=)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTnormrange2',
            field=models.FloatField(default=1, verbose_name='判断标准二适用范围(>)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTnormstandard1',
            field=models.FloatField(default=1, verbose_name='判断标准一(差值)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTnormstandard2',
            field=models.FloatField(default=1, verbose_name='判断标准二(比值)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptbackstage',
            name='PTunit',
            field=models.CharField(default='', max_length=20, verbose_name='单位'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ptmain',
            name='project',
            field=models.CharField(max_length=10, verbose_name='项目'),
        ),
    ]
