# Generated by Django 3.0.5 on 2020-06-01 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20200528_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '通用性参数设置',
                'verbose_name_plural': '通用性参数设置',
            },
        ),
        migrations.AlterField(
            model_name='ptbackstage',
            name='PTnormrange1',
            field=models.FloatField(verbose_name='判断标准一适用范围(<)'),
        ),
        migrations.AlterField(
            model_name='ptbackstage',
            name='PTnormrange2',
            field=models.FloatField(verbose_name='判断标准二适用范围(>=)'),
        ),
        migrations.CreateModel(
            name='subindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=32, verbose_name='子验证指标')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.general')),
            ],
            options={
                'verbose_name': '子验证指标',
                'verbose_name_plural': '子验证指标',
            },
        ),
    ]
