# Generated by Django 3.0.5 on 2020-06-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20200601_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='index',
            field=models.CharField(default='', max_length=32, verbose_name='验证指标'),
            preserve_default=False,
        ),
    ]
