# Generated by Django 3.0.5 on 2020-06-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_auto_20200601_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseparameterPJjmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseparameter', models.CharField(max_length=32, verbose_name='基本参数')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.CreateModel(
            name='baseparameterPNjmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseparameter', models.CharField(max_length=32, verbose_name='基本参数')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.CreateModel(
            name='PJjmdbackstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '批间精密度',
                'verbose_name_plural': '批间精密度',
            },
        ),
        migrations.CreateModel(
            name='PNjmdbackstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '批内精密度',
                'verbose_name_plural': '批内精密度',
            },
        ),
        migrations.RemoveField(
            model_name='jmdbackstage',
            name='index',
        ),
        migrations.RemoveField(
            model_name='textjmd',
            name='jmdbackstage',
        ),
        migrations.DeleteModel(
            name='baseparameterjmd',
        ),
        migrations.AddField(
            model_name='pnjmdbackstage',
            name='jmdbackstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.jmdbackstage', verbose_name='通用性参数设置'),
        ),
        migrations.AddField(
            model_name='pjjmdbackstage',
            name='jmdbackstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.jmdbackstage', verbose_name='通用性参数设置'),
        ),
        migrations.AddField(
            model_name='baseparameterpnjmd',
            name='PNjmdbackstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PNjmdbackstage'),
        ),
        migrations.AddField(
            model_name='baseparameterpjjmd',
            name='PJjmdbackstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PJjmdbackstage'),
        ),
        migrations.AddField(
            model_name='textjmd',
            name='PJjmdbackstage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.PJjmdbackstage'),
            preserve_default=False,
        ),
    ]
