# Generated by Django 3.0.5 on 2020-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_auto_20200601_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjjmdbackstage',
            name='name',
            field=models.CharField(default='批间精密度', max_length=32, verbose_name='批间精密度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnjmdbackstage',
            name='name',
            field=models.CharField(default='批内精密度', max_length=32, verbose_name='批内精密度'),
            preserve_default=False,
        ),
    ]
