# Generated by Django 3.0.5 on 2020-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_auto_20200601_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='name',
            field=models.CharField(default='通用性参数设置', max_length=32, verbose_name='通用性参数设置'),
            preserve_default=False,
        ),
    ]
