# Generated by Django 3.0.5 on 2020-06-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_general_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmdbackstage',
            name='index',
            field=models.CharField(default='精密度', max_length=32, verbose_name='子验证指标'),
            preserve_default=False,
        ),
    ]
