# Generated by Django 3.0.5 on 2020-06-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_jmdbackstage_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparameterpjjmd',
            name='PJjmdbackstage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PJjmdbackstage'),
        ),
        migrations.AlterField(
            model_name='baseparameterpnjmd',
            name='PNjmdbackstage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PNjmdbackstage'),
        ),
        migrations.AlterField(
            model_name='jmdbackstage',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.general', verbose_name='通用性参数设置'),
        ),
        migrations.AlterField(
            model_name='pjjmdbackstage',
            name='jmdbackstage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.jmdbackstage', verbose_name='通用性参数设置'),
        ),
        migrations.AlterField(
            model_name='pnjmdbackstage',
            name='jmdbackstage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.jmdbackstage', verbose_name='通用性参数设置'),
        ),
        migrations.AlterField(
            model_name='textpnjmd',
            name='PNjmdbackstage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PNjmdbackstage'),
        ),
    ]
