# Generated by Django 3.0.5 on 2020-06-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_auto_20200601_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparameterpnjmd',
            name='PNjmdbackstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PNjmdbackstage'),
        ),
        migrations.AlterField(
            model_name='textpnjmd',
            name='PNjmdbackstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PNjmdbackstage'),
        ),
    ]
