# Generated by Django 3.0.5 on 2020-06-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_auto_20200601_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparameterpjjmd',
            name='PJjmdbackstage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PJjmdbackstage'),
        ),
    ]
