# Generated by Django 3.0.5 on 2020-06-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_auto_20200602_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmdbackstage',
            name='index',
            field=models.CharField(default='', max_length=32, verbose_name='子验证指标'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pjjmdbackstage',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='批间精密度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnjmdbackstage',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='批内精密度'),
            preserve_default=False,
        ),
    ]
