# Generated by Django 3.0.5 on 2020-06-02 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_auto_20200602_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmdbackstage',
            name='general',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.general', verbose_name='通用性参数设置'),
        ),
    ]
