# Generated by Django 3.0.5 on 2020-06-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0039_auto_20200602_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_made', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='baseparameterpnjmd',
            name='PNjmdbackstage',
        ),
        migrations.RemoveField(
            model_name='jmdbackstage',
            name='general',
        ),
        migrations.RemoveField(
            model_name='pjjmdbackstage',
            name='jmdbackstage',
        ),
        migrations.RemoveField(
            model_name='pnjmdbackstage',
            name='jmdbackstage',
        ),
        migrations.RemoveField(
            model_name='textpjjmd',
            name='PJjmdbackstage',
        ),
        migrations.RemoveField(
            model_name='textpnjmd',
            name='PNjmdbackstage',
        ),
        migrations.DeleteModel(
            name='baseparameterPJjmd',
        ),
        migrations.DeleteModel(
            name='baseparameterPNjmd',
        ),
        migrations.DeleteModel(
            name='general',
        ),
        migrations.DeleteModel(
            name='jmdbackstage',
        ),
        migrations.DeleteModel(
            name='PJjmdbackstage',
        ),
        migrations.DeleteModel(
            name='PNjmdbackstage',
        ),
        migrations.DeleteModel(
            name='textPJjmd',
        ),
        migrations.DeleteModel(
            name='textPNjmd',
        ),
        migrations.AddField(
            model_name='friends',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Person'),
        ),
    ]
