# Generated by Django 3.0.5 on 2020-06-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0040_auto_20200602_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.CharField(max_length=100)),
                ('field_two', models.CharField(max_length=200)),
                ('field_three', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_field', models.CharField(max_length=50)),
                ('relation_model_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ModelOne')),
            ],
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
