# Generated by Django 3.0.5 on 2020-06-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0043_auto_20200602_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='text',
        ),
        migrations.AddField(
            model_name='method',
            name='minpass',
            field=models.FloatField(default=80, verbose_name='最低通过率(%)(PT需填写此项)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='recyclelow',
            field=models.FloatField(default=85, verbose_name='回收率下限(%)(加标回收率需填写此项)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='recycleup',
            field=models.FloatField(default=115, verbose_name='回收率上限(%)(加标回收率需填写此项)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='method',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Item', verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='method',
            name='maxCV',
            field=models.FloatField(verbose_name='最大允许CV(%)(精密度需填写此项)'),
        ),
        migrations.AlterField(
            model_name='method',
            name='minSample',
            field=models.FloatField(verbose_name='所需最小样本数(精密度,PT需填写此项)'),
        ),
        migrations.CreateModel(
            name='texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='描述性内容(所有指标均需填写此项)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Item', verbose_name='项目名称')),
            ],
        ),
    ]
