# Generated by Django 3.0.5 on 2020-06-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0044_auto_20200602_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNjmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '批内精密度',
                'verbose_name_plural': '批内精密度',
            },
        ),
        migrations.CreateModel(
            name='PNjmdMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minSample', models.FloatField(verbose_name='所需最小样本数')),
                ('maxCV', models.FloatField(verbose_name='最大允许CV(%)')),
                ('PNjmd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PNjmd', verbose_name='批内精密度')),
            ],
            options={
                'verbose_name': '批内精密度基本参数',
                'verbose_name_plural': '批内精密度基本参数',
            },
        ),
        migrations.CreateModel(
            name='PNjmdtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='描述性内容')),
                ('PNjmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PNjmd', verbose_name='批内精密度')),
            ],
        ),
        migrations.RemoveField(
            model_name='method',
            name='item',
        ),
        migrations.RemoveField(
            model_name='texts',
            name='item',
        ),
        migrations.RemoveField(
            model_name='general',
            name='name',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='texts',
        ),
        migrations.AddField(
            model_name='pnjmd',
            name='general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.general', verbose_name='批内精密度'),
        ),
    ]
