# Generated by Django 3.0.5 on 2020-06-03 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0047_auto_20200603_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnjmd',
            name='general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='通用性参数设置'),
        ),
        migrations.AlterField(
            model_name='pnjmd',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='批内精密度'),
        ),
    ]
