# Generated by Django 3.0.5 on 2020-06-03 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0050_auto_20200603_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJjmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='此框留空')),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='通用性参数设置')),
            ],
            options={
                'verbose_name': '批间精密度',
                'verbose_name_plural': '批间精密度',
            },
        ),
        migrations.AlterField(
            model_name='pnjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='通用性参数设置'),
        ),
        migrations.AlterField(
            model_name='pnjmd',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='此框留空'),
        ),
        migrations.CreateModel(
            name='PJjmdtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='描述性内容')),
                ('pJjmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PJjmd', verbose_name='批间精密度')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='PJjmdMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minSample', models.FloatField(verbose_name='所需最小样本数')),
                ('maxCV', models.FloatField(verbose_name='最大允许CV(%)')),
                ('pJjmd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PJjmd', verbose_name='批间精密度')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
    ]
