# Generated by Django 3.0.5 on 2020-06-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0054_auto_20200603_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': '方法学报告性能验证指标', 'verbose_name_plural': '方法学报告性能验证指标'},
        ),
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(max_length=32, verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pjjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pnjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='ptback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recycleback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.CreateModel(
            name='PTback2unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单位')),
                ('pTback2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PTback2', verbose_name='PT')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
        ),
        migrations.CreateModel(
            name='PTback2accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(blank=True, max_length=32, verbose_name='化合物名称')),
                ('range1', models.FloatField(blank=True, verbose_name='可接受标准一适用范围(<=)')),
                ('accept1', models.FloatField(blank=True, verbose_name='可接受标准一(差值)')),
                ('range2', models.FloatField(blank=True, verbose_name='可接受标准二适用范围(>)')),
                ('accept2', models.FloatField(blank=True, verbose_name='可接受标准二(比值%)')),
                ('pTback2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PTback2', verbose_name='PT')),
            ],
            options={
                'verbose_name': '可接受标准',
                'verbose_name_plural': '可接受标准',
            },
        ),
    ]
