# Generated by Django 3.0.5 on 2020-06-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0060_auto_20200612_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnjmdmethod',
            name='pNjmd',
        ),
        migrations.RemoveField(
            model_name='pnjmdtexts',
            name='pNjmd',
        ),
        migrations.AddField(
            model_name='pnjmdmethod',
            name='PNJMD_key',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.PNJMD', verbose_name='重复性精密度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnjmdtexts',
            name='PNJMD_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.PNJMD', verbose_name='重复性精密度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amrback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pjjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pnjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recycleback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
    ]
