# Generated by Django 3.0.5 on 2020-06-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0064_auto_20200612_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amrbackmethod',
            name='aMRback',
        ),
        migrations.RemoveField(
            model_name='amrbacktexts',
            name='aMRback',
        ),
        migrations.RenameField(
            model_name='ptbackmethod',
            old_name='pTback',
            new_name='PTback_key',
        ),
        migrations.RenameField(
            model_name='ptbacktexts',
            old_name='pTback',
            new_name='PTback_key',
        ),
        migrations.RemoveField(
            model_name='recyclebackmethod',
            name='recycleback',
        ),
        migrations.RemoveField(
            model_name='recyclebacktexts',
            name='recycleback',
        ),
        migrations.AddField(
            model_name='recyclebackmethod',
            name='RECYCLEback_key',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='report.RECYCLEback', verbose_name='加标回收率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recyclebacktexts',
            name='RECYCLEback_key',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='report.RECYCLEback', verbose_name='加标回收率'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pjjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pjjmdmethod',
            name='PJJMD_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PJJMD', verbose_name='中间精密度'),
        ),
        migrations.AlterField(
            model_name='pjjmdtexts',
            name='PJJMD_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PJJMD', verbose_name='中间精密度'),
        ),
        migrations.AlterField(
            model_name='pnjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pnjmdmethod',
            name='PNJMD_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PNJMD', verbose_name='重复性精密度'),
        ),
        migrations.AlterField(
            model_name='pnjmdtexts',
            name='PNJMD_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PNJMD', verbose_name='重复性精密度'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='ptbackmethod',
            name='minPass',
            field=models.FloatField(blank=True, verbose_name='最低通过率CV(%)'),
        ),
        migrations.AlterField(
            model_name='ptbackmethod',
            name='minSample',
            field=models.FloatField(blank=True, verbose_name='所需最小样本数'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recycleback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.DeleteModel(
            name='AMRback',
        ),
        migrations.DeleteModel(
            name='AMRbackMethod',
        ),
        migrations.DeleteModel(
            name='AMRbacktexts',
        ),
    ]
