# Generated by Django 3.0.5 on 2020-06-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0067_auto_20200617_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNJMDMethodteshu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minSample', models.FloatField(verbose_name='所需最小样本数')),
                ('maxCV', models.FloatField(verbose_name='最大允许CV(%)')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.CreateModel(
            name='PNJMDtextsteshu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, verbose_name='描述性内容')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.RemoveField(
            model_name='pnjmd2texts',
            name='pNjmd2',
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pjjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pjjmdmethod',
            name='PJJMD_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PJJMD', verbose_name='中间精密度'),
        ),
        migrations.AlterField(
            model_name='pjjmdtexts',
            name='PJJMD_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PJJMD', verbose_name='中间精密度'),
        ),
        migrations.AlterField(
            model_name='pnjmd',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pnjmdmethod',
            name='PNJMD_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PNJMD', verbose_name='重复性精密度'),
        ),
        migrations.AlterField(
            model_name='pnjmdtexts',
            name='PNJMD_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PNJMD', verbose_name='重复性精密度'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recycleback',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recyclebackmethod',
            name='RECYCLEback_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.RECYCLEback', verbose_name='加标回收率'),
        ),
        migrations.AlterField(
            model_name='recyclebacktexts',
            name='RECYCLEback_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.RECYCLEback', verbose_name='加标回收率'),
        ),
        migrations.RenameModel(
            old_name='PNjmd2',
            new_name='PNJMDteshu',
        ),
        migrations.DeleteModel(
            name='PNjmd2Method',
        ),
        migrations.DeleteModel(
            name='PNjmd2texts',
        ),
        migrations.AddField(
            model_name='pnjmdtextsteshu',
            name='PNJMDteshu_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PNJMDteshu', verbose_name='重复性精密度'),
        ),
        migrations.AddField(
            model_name='pnjmdmethodteshu',
            name='PNJMDteshu_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PNJMDteshu', verbose_name='重复性精密度'),
        ),
    ]
