# Generated by Django 3.0.5 on 2020-06-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0071_auto_20200618_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.CreateModel(
            name='AMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experimentnum', models.CharField(max_length=32)),
                ('norm', models.CharField(max_length=32)),
                ('therory_conc', models.FloatField()),
                ('test_conc1', models.FloatField()),
                ('test_conc2', models.FloatField()),
                ('test_conc3', models.FloatField()),
                ('test_conc4', models.FloatField()),
                ('test_conc5', models.FloatField()),
                ('test_conc6', models.FloatField()),
                ('recycle1', models.FloatField()),
                ('recycle2', models.FloatField()),
                ('recycle3', models.FloatField()),
                ('recycle4', models.FloatField()),
                ('recycle5', models.FloatField()),
                ('recycle6', models.FloatField()),
                ('meanrecycle', models.FloatField()),
                ('cvtest_conc', models.FloatField()),
                ('reportinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo')),
            ],
        ),
    ]
