# Generated by Django 3.0.5 on 2020-06-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0075_auto_20200618_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr',
            name='cvtest_conc',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='meanrecycle',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='recycle1',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='recycle2',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='recycle3',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='recycle4',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='recycle5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='recycle6',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amr',
            name='test_conc1',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='test_conc2',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='test_conc3',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='test_conc4',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='test_conc5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='test_conc6',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amr',
            name='therory_conc',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='amrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
    ]
