# Generated by Django 3.0.5 on 2020-06-24 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0077_auto_20200622_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMRspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='子验证指标')),
                ('special', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置')),
            ],
            options={
                'verbose_name': 'AMR',
                'verbose_name_plural': 'AMR',
            },
        ),
        migrations.CreateModel(
            name='CRRgeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='子验证指标')),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标')),
            ],
            options={
                'verbose_name': 'CRR',
                'verbose_name_plural': 'CRR',
            },
        ),
        migrations.CreateModel(
            name='CRRspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='子验证指标')),
                ('special', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置')),
            ],
            options={
                'verbose_name': 'CRR',
                'verbose_name_plural': 'CRR',
            },
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='amrgeneraltexts',
            name='text',
            field=models.TextField(max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneraltexts',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='interprecisionspecialtexts',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='ptgeneraltexts',
            name='text',
            field=models.TextField(max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='ptspecialtexts',
            name='text',
            field=models.TextField(max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recyclegeneraltexts',
            name='text',
            field=models.TextField(max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='recyclespecialtexts',
            name='text',
            field=models.TextField(max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneraltexts',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='描述性内容'),
        ),
        migrations.AlterField(
            model_name='repeatprecisionspecialtexts',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='描述性内容'),
        ),
        migrations.CreateModel(
            name='CRRspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('cRRspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.CRRspecial', verbose_name='CRR')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='CRRspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowvalue', models.FloatField(blank=True, verbose_name='回收率下限(%)')),
                ('upvalue', models.FloatField(blank=True, verbose_name='回收率上限(%)')),
                ('cRRspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.CRRspecial', verbose_name='CRR')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.CreateModel(
            name='CRRgeneraltexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('cRRgeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.CRRgeneral', verbose_name='AMR')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='CRRgeneralmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowvalue', models.FloatField(blank=True, verbose_name='回收率下限(%)')),
                ('upvalue', models.FloatField(blank=True, verbose_name='回收率上限(%)')),
                ('cRRgeneral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.CRRgeneral', verbose_name='AMR')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.CreateModel(
            name='CRR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dilution', models.CharField(max_length=32)),
                ('norm', models.CharField(max_length=32)),
                ('test_conc1', models.CharField(max_length=32)),
                ('test_conc2', models.CharField(max_length=32)),
                ('test_conc3', models.CharField(max_length=32)),
                ('test_conc4', models.CharField(max_length=32)),
                ('test_conc5', models.CharField(max_length=32)),
                ('calresults', models.CharField(max_length=32)),
                ('reportinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AMRspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('aMRspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.AMRspecial', verbose_name='AMR')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='AMRspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowvalue', models.FloatField(blank=True, verbose_name='回收率下限(%)')),
                ('upvalue', models.FloatField(blank=True, verbose_name='回收率上限(%)')),
                ('cv', models.FloatField(blank=True, verbose_name='cv(%)')),
                ('aMRspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.AMRspecial', verbose_name='AMR')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
    ]
