# Generated by Django 3.0.5 on 2020-06-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0078_auto_20200624_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSgeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='子验证指标')),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标')),
            ],
            options={
                'verbose_name': '基质特异性',
                'verbose_name_plural': '基质特异性',
            },
        ),
        migrations.CreateModel(
            name='MSspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='子验证指标')),
                ('special', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置')),
            ],
            options={
                'verbose_name': '基质特异性',
                'verbose_name_plural': '基质特异性',
            },
        ),
        migrations.AlterModelOptions(
            name='amrgeneral',
            options={'verbose_name': '线性测量范围', 'verbose_name_plural': '线性测量范围'},
        ),
        migrations.AlterModelOptions(
            name='crrgeneral',
            options={'verbose_name': '临床可报告范围', 'verbose_name_plural': '临床可报告范围'},
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='crrgeneralmethod',
            name='cRRgeneral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.CRRgeneral', verbose_name='CRR'),
        ),
        migrations.AlterField(
            model_name='crrgeneraltexts',
            name='cRRgeneral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.CRRgeneral', verbose_name='CRR'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.CreateModel(
            name='MSspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('mSspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.MSspecial', verbose_name='基质特异性')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='MSgeneraltexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('mSgeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.MSgeneral', verbose_name='基质特异性')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='img')),
                ('name', models.CharField(max_length=32)),
                ('reportinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo')),
            ],
        ),
    ]
