# Generated by Django 3.0.5 on 2020-07-17 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0091_auto_20200716_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detectionmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '检测方法',
                'verbose_name_plural': '检测方法',
            },
        ),
        migrations.AlterModelOptions(
            name='amrgeneral',
            options={'verbose_name': '分析灵敏度与分析测量范围', 'verbose_name_plural': '分析灵敏度与分析测量范围'},
        ),
        migrations.AlterModelOptions(
            name='amrspecial',
            options={'verbose_name': '线性灵敏度和线性测量范围', 'verbose_name_plural': '线性灵敏度和线性测量范围'},
        ),
        migrations.AlterModelOptions(
            name='crrspecial',
            options={'verbose_name': '临床可报告范围', 'verbose_name_plural': '临床可报告范围'},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': '各项目方法学参数', 'verbose_name_plural': '各项目方法学参数'},
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='amrgeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryovergeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='carryovergeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='carryoverspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='crrgeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='crrspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(max_length=32, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='interprecisionspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffectgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='matrixeffectgeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='matrixeffectspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='msgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='msgeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='msspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='ptspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='recyclespecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisionspecial',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='验证指标'),
        ),
        migrations.AlterField(
            model_name='special',
            name='group',
            field=models.CharField(max_length=32, verbose_name='项目名称'),
        ),
        migrations.CreateModel(
            name='LC_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='平台名称')),
                ('detectionmethod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Detectionmethod', verbose_name='液相色谱串联质谱平台')),
            ],
            options={
                'verbose_name': '液相色谱串联质谱平台',
                'verbose_name_plural': '液相色谱串联质谱平台',
            },
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='平台名称')),
                ('detectionmethod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Detectionmethod', verbose_name='液相色谱平台')),
            ],
            options={
                'verbose_name': '液相色谱平台',
                'verbose_name_plural': '液相色谱平台',
            },
        ),
        migrations.CreateModel(
            name='ICP_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='平台名称')),
                ('detectionmethod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Detectionmethod', verbose_name='电感耦合等离子体质谱平台')),
            ],
            options={
                'verbose_name': '电感耦合等离子体质谱平台',
                'verbose_name_plural': '电感耦合等离子体质谱平台',
            },
        ),
        migrations.CreateModel(
            name='GC_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='平台名称')),
                ('detectionmethod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Detectionmethod', verbose_name='气相色谱串联质谱平台')),
            ],
            options={
                'verbose_name': '气相色谱串联质谱平台',
                'verbose_name_plural': '气相色谱串联质谱平台',
            },
        ),
    ]
