# Generated by Django 3.0.5 on 2020-07-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0097_auto_20200717_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_AB_LC_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
            },
        ),
        migrations.AlterModelOptions(
            name='ab_lc_ms',
            options={'verbose_name': 'AB', 'verbose_name_plural': 'AB'},
        ),
        migrations.AlterModelOptions(
            name='agilent_lc_ms',
            options={'verbose_name': 'Agilent', 'verbose_name_plural': 'Agilent'},
        ),
        migrations.AlterModelOptions(
            name='lc_ms',
            options={'verbose_name': '液相色谱串联质谱平台', 'verbose_name_plural': '液相色谱串联质谱平台'},
        ),
        migrations.AlterModelOptions(
            name='shimadzu_lc_ms',
            options={'verbose_name': 'Shimadzu', 'verbose_name_plural': 'Shimadzu'},
        ),
        migrations.AlterField(
            model_name='ab_lc_ms',
            name='lC_MS',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LC_MS', verbose_name='液相色谱串联质谱平台'),
        ),
        migrations.AlterField(
            model_name='agilent_lc_ms',
            name='lC_MS',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LC_MS', verbose_name='液相色谱串联质谱平台'),
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryovergeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lc_ms',
            name='detectionmethod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Detectionmethod', verbose_name='检测方法'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffectgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='msgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='shimadzu_lc_ms',
            name='lC_MS',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.LC_MS', verbose_name='液相色谱串联质谱平台'),
        ),
        migrations.CreateModel(
            name='ZP_Project_AB_LC_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='质谱方法')),
                ('project_AB_LC_MS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Project_AB_LC_MS', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '质谱方法',
                'verbose_name_plural': '质谱方法',
            },
        ),
        migrations.CreateModel(
            name='YX_Project_AB_LC_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='液相方法')),
                ('project_AB_LC_MS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Project_AB_LC_MS', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '液相方法',
                'verbose_name_plural': '液相方法',
            },
        ),
        migrations.AddField(
            model_name='project_ab_lc_ms',
            name='aB_LC_MS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.AB_LC_MS', verbose_name='AB'),
        ),
    ]
