# Generated by Django 3.0.5 on 2020-08-05 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0115_auto_20200804_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agilent_lc_ms',
            name='lC_MS',
        ),
        migrations.RemoveField(
            model_name='gc_ms',
            name='detectionmethod',
        ),
        migrations.RemoveField(
            model_name='icp_ms',
            name='detectionmethod',
        ),
        migrations.RemoveField(
            model_name='lc',
            name='detectionmethod',
        ),
        migrations.RemoveField(
            model_name='lc_ms',
            name='detectionmethod',
        ),
        migrations.RemoveField(
            model_name='project_ab_lc_ms',
            name='aB_LC_MS',
        ),
        migrations.RemoveField(
            model_name='project_agilent_lc_ms',
            name='agilent_LC_MS',
        ),
        migrations.RemoveField(
            model_name='project_shimadzu_lc_ms',
            name='shimadzu_LC_MS',
        ),
        migrations.RemoveField(
            model_name='shimadzu_lc_ms',
            name='lC_MS',
        ),
        migrations.RemoveField(
            model_name='yx_project_ab_lc_ms',
            name='project_AB_LC_MS',
        ),
        migrations.RemoveField(
            model_name='yx_project_agilent_lc_ms',
            name='project_Agilent_LC_MS',
        ),
        migrations.RemoveField(
            model_name='yx_project_shimadzu_lc_ms',
            name='project_Shimadzu_LC_MS',
        ),
        migrations.RemoveField(
            model_name='yx_texts_project_ab_lc_ms',
            name='project_AB_LC_MS',
        ),
        migrations.RemoveField(
            model_name='zp_project_ab_lc_ms',
            name='project_AB_LC_MS',
        ),
        migrations.RemoveField(
            model_name='zp_project_agilent_lc_ms',
            name='project_Agilent_LC_MS',
        ),
        migrations.RemoveField(
            model_name='zp_project_shimadzu_lc_ms',
            name='project_Shimadzu_LC_MS',
        ),
        migrations.RemoveField(
            model_name='zp_texts_project_ab_lc_ms',
            name='project_AB_LC_MS',
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrconsluion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryovergeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='name',
            field=models.CharField(max_length=32, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crrgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='interprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lod',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffectgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='msgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptgeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='name',
            field=models.CharField(max_length=32, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclegeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='repeatprecisiongeneral',
            name='general',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标'),
        ),
        migrations.AlterField(
            model_name='validation_reason',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.DeleteModel(
            name='AB_LC_MS',
        ),
        migrations.DeleteModel(
            name='Agilent_LC_MS',
        ),
        migrations.DeleteModel(
            name='GC_MS',
        ),
        migrations.DeleteModel(
            name='ICP_MS',
        ),
        migrations.DeleteModel(
            name='LC',
        ),
        migrations.DeleteModel(
            name='LC_MS',
        ),
        migrations.DeleteModel(
            name='Project_AB_LC_MS',
        ),
        migrations.DeleteModel(
            name='Project_Agilent_LC_MS',
        ),
        migrations.DeleteModel(
            name='Project_Shimadzu_LC_MS',
        ),
        migrations.DeleteModel(
            name='Shimadzu_LC_MS',
        ),
        migrations.DeleteModel(
            name='YX_Project_AB_LC_MS',
        ),
        migrations.DeleteModel(
            name='YX_Project_Agilent_LC_MS',
        ),
        migrations.DeleteModel(
            name='YX_Project_Shimadzu_LC_MS',
        ),
        migrations.DeleteModel(
            name='YX_texts_Project_AB_LC_MS',
        ),
        migrations.DeleteModel(
            name='ZP_Project_AB_LC_MS',
        ),
        migrations.DeleteModel(
            name='ZP_Project_Agilent_LC_MS',
        ),
        migrations.DeleteModel(
            name='ZP_Project_Shimadzu_LC_MS',
        ),
        migrations.DeleteModel(
            name='ZP_texts_Project_AB_LC_MS',
        ),
    ]
