# Generated by Django 3.0.5 on 2020-11-04 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0146_auto_20200918_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amrspecial',
            options={'verbose_name': '', 'verbose_name_plural': '线性灵敏度和线性测量范围'},
        ),
        migrations.AlterModelOptions(
            name='carryoverspecial',
            options={'verbose_name': '', 'verbose_name_plural': '携带效应'},
        ),
        migrations.AlterModelOptions(
            name='crrspecial',
            options={'verbose_name': '', 'verbose_name_plural': '临床可报告范围'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '项目名称', 'verbose_name_plural': '4 设备'},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': '通用性参数设置', 'verbose_name_plural': '1 通用性参数设置'},
        ),
        migrations.AlterModelOptions(
            name='interprecisionspecial',
            options={'verbose_name': '', 'verbose_name_plural': '中间精密度'},
        ),
        migrations.AlterModelOptions(
            name='matrixeffectspecial',
            options={'verbose_name': '', 'verbose_name_plural': '基质效应'},
        ),
        migrations.AlterModelOptions(
            name='msspecial',
            options={'verbose_name': '', 'verbose_name_plural': '基质特异性'},
        ),
        migrations.AlterModelOptions(
            name='ptspecial',
            options={'verbose_name': '', 'verbose_name_plural': 'PT'},
        ),
        migrations.AlterModelOptions(
            name='reagents_consumables',
            options={'verbose_name': '项目名称', 'verbose_name_plural': '5 试剂耗材'},
        ),
        migrations.AlterModelOptions(
            name='recyclespecial',
            options={'verbose_name': '', 'verbose_name_plural': '加标回收率'},
        ),
        migrations.AlterModelOptions(
            name='repeatprecisionspecial',
            options={'verbose_name': '', 'verbose_name_plural': '重复性精密度'},
        ),
        migrations.AlterModelOptions(
            name='sample_preparation',
            options={'verbose_name': '项目名称', 'verbose_name_plural': '6 样品处理'},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': '各项目参数设置', 'verbose_name_plural': '2 各项目参数设置'},
        ),
        migrations.AlterModelOptions(
            name='testmethod',
            options={'verbose_name': '仪器条件', 'verbose_name_plural': '3 仪器条件'},
        ),
        migrations.AddField(
            model_name='testmethod',
            name='group',
            field=models.CharField(default='', max_length=16, verbose_name='项目组'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrconsluion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='endconclusion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lod',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='validation_reason',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
    ]
