# Generated by Django 3.0.5 on 2020-12-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0153_auto_20201201_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='JCXspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='验证指标')),
                ('special', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置')),
            ],
            options={
                'verbose_name': '检出限',
                'verbose_name_plural': '检出限',
            },
        ),
        migrations.AlterModelOptions(
            name='amrspecial',
            options={'verbose_name': '线性灵敏度和线性测量范围', 'verbose_name_plural': '线性灵敏度和线性测量范围'},
        ),
        migrations.AlterModelOptions(
            name='carryoverspecial',
            options={'verbose_name': '携带效应', 'verbose_name_plural': '携带效应'},
        ),
        migrations.AlterModelOptions(
            name='crrspecial',
            options={'verbose_name': '临床可报告范围', 'verbose_name_plural': '临床可报告范围'},
        ),
        migrations.AlterModelOptions(
            name='interprecisionspecial',
            options={'verbose_name': '中间精密度', 'verbose_name_plural': '中间精密度'},
        ),
        migrations.AlterModelOptions(
            name='matrixeffectspecial',
            options={'verbose_name': '基质效应', 'verbose_name_plural': '基质效应'},
        ),
        migrations.AlterModelOptions(
            name='msspecial',
            options={'verbose_name': '基质特异性', 'verbose_name_plural': '基质特异性'},
        ),
        migrations.AlterModelOptions(
            name='ptspecial',
            options={'verbose_name': 'PT', 'verbose_name_plural': 'PT'},
        ),
        migrations.AlterModelOptions(
            name='recyclespecial',
            options={'verbose_name': '加标回收率', 'verbose_name_plural': '加标回收率'},
        ),
        migrations.AlterModelOptions(
            name='repeatprecisionspecial',
            options={'verbose_name': '重复性精密度', 'verbose_name_plural': '重复性精密度'},
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrconsluion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrspecialmethod',
            name='cv',
            field=models.FloatField(blank=True, verbose_name='最大允许CV(%)'),
        ),
        migrations.AlterField(
            model_name='amrspecialmethod',
            name='lowvalue',
            field=models.FloatField(blank=True, verbose_name='回收率下限(%)'),
        ),
        migrations.AlterField(
            model_name='amrspecialmethod',
            name='upvalue',
            field=models.FloatField(blank=True, verbose_name='回收率上限(%)'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryoverspecialmethod',
            name='accept',
            field=models.FloatField(blank=True, verbose_name='可接受标准(%)'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crrspecialmethod',
            name='lowvalue',
            field=models.FloatField(blank=True, verbose_name='回收率下限(%)'),
        ),
        migrations.AlterField(
            model_name='crrspecialmethod',
            name='upvalue',
            field=models.FloatField(blank=True, verbose_name='回收率上限(%)'),
        ),
        migrations.AlterField(
            model_name='endconclusion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='interprecisionspecialmethod',
            name='maxCV',
            field=models.FloatField(blank=True, verbose_name='最大允许CV(%)'),
        ),
        migrations.AlterField(
            model_name='interprecisionspecialmethod',
            name='minSample',
            field=models.IntegerField(blank=True, verbose_name='所需最小样本数'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lod',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lodpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffectgeneralmethod',
            name='bias',
            field=models.FloatField(verbose_name='最大允许偏差(%)'),
        ),
        migrations.AlterField(
            model_name='matrixeffectspecialmethod',
            name='bias',
            field=models.FloatField(blank=True, verbose_name='最大允许偏差(%)'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ptspecialmethod',
            name='minPass',
            field=models.FloatField(blank=True, verbose_name='最低通过率CV(%)'),
        ),
        migrations.AlterField(
            model_name='ptspecialmethod',
            name='minSample',
            field=models.IntegerField(blank=True, verbose_name='所需最小样本数'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recyclespecialmethod',
            name='lowvalue',
            field=models.FloatField(blank=True, verbose_name='回收率下限(%)'),
        ),
        migrations.AlterField(
            model_name='recyclespecialmethod',
            name='upvalue',
            field=models.FloatField(blank=True, verbose_name='回收率上限(%)'),
        ),
        migrations.AlterField(
            model_name='repeatprecisionspecialmethod',
            name='maxCV',
            field=models.FloatField(blank=True, verbose_name='最大允许CV(%)'),
        ),
        migrations.AlterField(
            model_name='repeatprecisionspecialmethod',
            name='minSample',
            field=models.IntegerField(blank=True, verbose_name='所需最小样本数'),
        ),
        migrations.AlterField(
            model_name='validation_reason',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.CreateModel(
            name='JCXspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('jCXspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.JCXspecial', verbose_name='JCX')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
    ]
