# Generated by Django 3.0.5 on 2021-04-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0156_auto_20210301_1549'),
        ('report', '0161_auto_20210408_1051'),
    ]

    operations = [
    ]
