# Generated by Django 3.0.5 on 2021-04-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0165_auto_20210424_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMRspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='线性灵敏度和线性范围', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '线性灵敏度和线性测量范围',
                'verbose_name_plural': '线性灵敏度和线性测量范围',
            },
        ),
        migrations.CreateModel(
            name='Carryoverspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='携带效应', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '携带效应',
                'verbose_name_plural': '携带效应',
            },
        ),
        migrations.CreateModel(
            name='CRRspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='临床可报告范围', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '临床可报告范围',
                'verbose_name_plural': '临床可报告范围',
            },
        ),
        migrations.CreateModel(
            name='Interprecisionspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='中间精密度', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '中间精密度',
                'verbose_name_plural': '中间精密度',
            },
        ),
        migrations.CreateModel(
            name='JCXspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='检出限', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '检出限',
                'verbose_name_plural': '检出限',
            },
        ),
        migrations.CreateModel(
            name='Matrixeffectspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='基质效应', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '基质效应',
                'verbose_name_plural': '基质效应',
            },
        ),
        migrations.CreateModel(
            name='MSspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='基质特异性', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '基质特异性',
                'verbose_name_plural': '基质特异性',
            },
        ),
        migrations.CreateModel(
            name='PTspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='PT', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': 'PT',
                'verbose_name_plural': 'PT',
            },
        ),
        migrations.CreateModel(
            name='Recyclespecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='加标回收率', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '加标回收率',
                'verbose_name_plural': '加标回收率',
            },
        ),
        migrations.CreateModel(
            name='Repeatprecisionspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='重复性精密度', editable=False, max_length=32, verbose_name='验证指标')),
            ],
            options={
                'verbose_name': '重复性精密度',
                'verbose_name_plural': '重复性精密度',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detectionplatform', models.CharField(choices=[('内分泌检测平台', '内分泌检测平台'), ('遗传代谢病检测平台', '遗传代谢病检测平台'), ('微量营养素检测平台', '微量营养素检测平台'), ('治疗药物检测平台', '治疗药物检测平台'), ('研发与创新平台', '研发与创新平台')], max_length=16, verbose_name='仪器平台')),
                ('project', models.CharField(max_length=32, unique=True, verbose_name='项目')),
                ('chinese_titie', models.TextField(blank=True, max_length=200, verbose_name='中文标题')),
                ('english_titie', models.TextField(blank=True, max_length=200, verbose_name='英文标题')),
                ('unit', models.CharField(max_length=200, verbose_name='单位')),
                ('Effective_digits', models.IntegerField(verbose_name='有效位数')),
                ('Number_of_compounds', models.IntegerField(verbose_name='化合物个数')),
            ],
            options={
                'verbose_name': '各项目参数设置',
                'verbose_name_plural': '2 各项目参数设置',
            },
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrconsluion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='endconclusion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lod',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lodpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='validation_reason',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.CreateModel(
            name='Repeatprecisionspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='描述性内容')),
                ('repeatprecisionspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Repeatprecisionspecial', verbose_name='重复性精密度')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Repeatprecisionspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minSample', models.IntegerField(blank=True, verbose_name='所需最小样本数')),
                ('maxCV', models.FloatField(blank=True, verbose_name='最大允许CV(%)')),
                ('repeatprecisionspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Repeatprecisionspecial', verbose_name='重复性精密度')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.AddField(
            model_name='repeatprecisionspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='Recyclespecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('recyclespecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Recyclespecial', verbose_name='加标回收率')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Recyclespecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowvalue', models.FloatField(blank=True, verbose_name='回收率下限(%)')),
                ('upvalue', models.FloatField(blank=True, verbose_name='回收率上限(%)')),
                ('recyclespecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Recyclespecial', verbose_name='加标回收率')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.AddField(
            model_name='recyclespecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='PTspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('pTspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PTspecial', verbose_name='PT')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='PTspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minSample', models.IntegerField(blank=True, verbose_name='所需最小样本数')),
                ('minPass', models.FloatField(blank=True, verbose_name='最低通过率CV(%)')),
                ('pTspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.PTspecial', verbose_name='PT')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.CreateModel(
            name='PTspecialaccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(blank=True, max_length=32, null=True, verbose_name='化合物名称')),
                ('unit', models.CharField(blank=True, max_length=32, null=True, verbose_name='单位')),
                ('digits', models.IntegerField(blank=True, null=True, verbose_name='有效位数')),
                ('range1', models.FloatField(blank=True, null=True, verbose_name='可接受标准一适用范围(<=)')),
                ('accept1', models.FloatField(blank=True, null=True, verbose_name='可接受标准一(差值)')),
                ('range2', models.FloatField(blank=True, null=True, verbose_name='可接受标准二适用范围(>)')),
                ('accept2', models.FloatField(blank=True, null=True, verbose_name='可接受标准二(比值%)')),
                ('pTspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.PTspecial', verbose_name='PT')),
            ],
            options={
                'verbose_name': '可接受标准',
                'verbose_name_plural': '可接受标准',
            },
        ),
        migrations.AddField(
            model_name='ptspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='MSspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('mSspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.MSspecial', verbose_name='基质特异性')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.AddField(
            model_name='msspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='Matrixeffectspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('matrixeffectspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Matrixeffectspecial', verbose_name='基质效应')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Matrixeffectspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.FloatField(blank=True, verbose_name='最大允许偏差(%)')),
                ('matrixeffectspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Matrixeffectspecial', verbose_name='基质效应')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.AddField(
            model_name='matrixeffectspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='JCXspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('jCXspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.JCXspecial', verbose_name='JCX')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.AddField(
            model_name='jcxspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='Interprecisionspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='描述性内容')),
                ('interprecisionspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Interprecisionspecial', verbose_name='中间精密度')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Interprecisionspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minSample', models.IntegerField(blank=True, verbose_name='所需最小样本数')),
                ('maxCV', models.FloatField(blank=True, verbose_name='最大允许CV(%)')),
                ('interprecisionspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Interprecisionspecial', verbose_name='中间精密度')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.AddField(
            model_name='interprecisionspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='CRRspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('cRRspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.CRRspecial', verbose_name='CRR')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='CRRspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowvalue', models.FloatField(blank=True, verbose_name='回收率下限(%)')),
                ('upvalue', models.FloatField(blank=True, verbose_name='回收率上限(%)')),
                ('cRRspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.CRRspecial', verbose_name='CRR')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.AddField(
            model_name='crrspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='Carryoverspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('carryoverspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Carryoverspecial', verbose_name='携带效应')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Carryoverspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.FloatField(blank=True, verbose_name='可接受标准(%)')),
                ('carryoverspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Carryoverspecial', verbose_name='携带效应')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.AddField(
            model_name='carryoverspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
        migrations.CreateModel(
            name='AMRspecialtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('aMRspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.AMRspecial', verbose_name='AMR')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='AMRspecialmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowvalue', models.FloatField(blank=True, verbose_name='回收率下限(%)')),
                ('upvalue', models.FloatField(blank=True, verbose_name='回收率上限(%)')),
                ('cv', models.FloatField(blank=True, verbose_name='最大允许CV(%)')),
                ('aMRspecial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.AMRspecial', verbose_name='AMR')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.AddField(
            model_name='amrspecial',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Special', verbose_name='特殊参数设置'),
        ),
    ]
