# Generated by Django 3.0.5 on 2021-04-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0167_auto_20210424_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('液质', '液质'), ('液相', '液相'), ('气相', '气相'), ('ICP-MS', 'ICP-MS')], max_length=16, verbose_name='仪器平台')),
                ('factory', models.CharField(choices=[('AB', 'AB'), ('Agilent', 'Agilent'), ('岛津', '岛津'), ('Thermo', 'Thermo'), ('Waters', 'Waters')], max_length=16, verbose_name='仪器厂家')),
                ('Detectionplatform', models.CharField(choices=[('内分泌检测平台', '内分泌检测平台'), ('遗传代谢病检测平台', '遗传代谢病检测平台'), ('微量营养素检测平台', '微量营养素检测平台'), ('治疗药物检测平台', '治疗药物检测平台'), ('研发与创新平台', '研发与创新平台')], max_length=16, verbose_name='仪器平台')),
                ('project', models.CharField(max_length=16, unique=True, verbose_name='项目名称')),
                ('column', models.CharField(blank=True, max_length=100, verbose_name='色谱柱')),
                ('Instrument_model', models.CharField(blank=True, max_length=100, verbose_name='仪器型号')),
            ],
            options={
                'verbose_name': '仪器条件',
                'verbose_name_plural': '3 仪器条件',
            },
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrconsluion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='endconclusion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lod',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lodpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='validation_reason',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.CreateModel(
            name='ZP_Methodtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('testmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Testmethod')),
            ],
            options={
                'verbose_name': '质谱方法描述性内容',
                'verbose_name_plural': '质谱方法描述性内容',
            },
        ),
        migrations.CreateModel(
            name='ZP_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(max_length=200, verbose_name='分析物名称')),
                ('precursor_ion', models.CharField(max_length=200, verbose_name='母离子(m/z)')),
                ('product_ion', models.CharField(max_length=200, verbose_name='子离子(m/z)')),
                ('Times', models.CharField(blank=True, max_length=200, verbose_name='Time(s)')),
                ('ConeV', models.CharField(blank=True, max_length=200, verbose_name='Cone(V)')),
                ('CollisionV', models.CharField(blank=True, max_length=200, verbose_name='Collision(V)')),
                ('testmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Testmethod')),
            ],
            options={
                'verbose_name': '质谱方法',
                'verbose_name_plural': '质谱方法',
            },
        ),
        migrations.CreateModel(
            name='YX_Methodtexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('testmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Testmethod')),
            ],
            options={
                'verbose_name': '液相方法描述性内容',
                'verbose_name_plural': '液相方法描述性内容',
            },
        ),
        migrations.CreateModel(
            name='YX_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, max_length=200, verbose_name='步骤')),
                ('time', models.CharField(blank=True, max_length=200, verbose_name='分析时间(min)')),
                ('Flowrate', models.CharField(blank=True, max_length=200, verbose_name='流速(mL/min)')),
                ('Mobile_phaseA', models.CharField(blank=True, max_length=200, verbose_name='流动相A')),
                ('Mobile_phaseB', models.CharField(blank=True, max_length=200, verbose_name='流动相B')),
                ('testmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Testmethod')),
            ],
            options={
                'verbose_name': '液相方法',
                'verbose_name_plural': '液相方法',
            },
        ),
    ]
