# Generated by Django 3.0.5 on 2021-04-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0169_auto_20210424_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagents_Consumables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detectionplatform', models.CharField(choices=[('内分泌检测平台', '内分泌检测平台'), ('遗传代谢病检测平台', '遗传代谢病检测平台'), ('微量营养素检测平台', '微量营养素检测平台'), ('治疗药物检测平台', '治疗药物检测平台'), ('研发与创新平台', '研发与创新平台')], max_length=16, verbose_name='检测平台')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '5 试剂耗材',
            },
        ),
        migrations.CreateModel(
            name='Sample_Preparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detectionplatform', models.CharField(choices=[('内分泌检测平台', '内分泌检测平台'), ('遗传代谢病检测平台', '遗传代谢病检测平台'), ('微量营养素检测平台', '微量营养素检测平台'), ('治疗药物检测平台', '治疗药物检测平台'), ('研发与创新平台', '研发与创新平台')], max_length=16, verbose_name='检测平台')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '6 样品处理',
            },
        ),
        migrations.AlterField(
            model_name='amr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrconsluion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='amrpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='carryover2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='crr2',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='endconclusion',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='jmd',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lod',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='lodpicture',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='matrixeffect',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='ms',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='pt',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.AlterField(
            model_name='validation_reason',
            name='reportinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo'),
        ),
        migrations.CreateModel(
            name='texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('sample_Preparation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Sample_Preparation', verbose_name='主要试剂')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '样品处理描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Reagents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('reagents_Consumables', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Reagents_Consumables', verbose_name='主要试剂')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '主要试剂描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('reagents_Consumables', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Reagents_Consumables', verbose_name='主要耗材')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '主要耗材描述性内容',
            },
        ),
    ]
