# Generated by Django 3.0.5 on 2021-09-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0172_amr_amrconsluion_amrpicture_carryover_carryover2_crr_crr2_endconclusion_jmd_lod_lodpicture_matrixeff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='general',
            table='general table',
        ),
    ]
