# Generated by Django 3.0.5 on 2022-01-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0173_auto_20210908_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stabilitygeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=32, verbose_name='验证指标')),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.General', verbose_name='方法学报告性能验证指标')),
            ],
            options={
                'verbose_name': '样品稳定性',
                'verbose_name_plural': '样品稳定性',
            },
        ),
        migrations.CreateModel(
            name='Stabilitygeneraltexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('stabilitygeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Stabilitygeneral', verbose_name='回收率')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Stabilitygeneralmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowvalue', models.FloatField(verbose_name='回收率下限(%)')),
                ('upvalue', models.FloatField(verbose_name='回收率上限(%)')),
                ('stabilitygeneral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.Stabilitygeneral', verbose_name='回收率')),
            ],
            options={
                'verbose_name': '基本参数',
                'verbose_name_plural': '基本参数',
            },
        ),
        migrations.CreateModel(
            name='Stability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(max_length=32)),
                ('samplenametemperature', models.CharField(max_length=32)),
                ('time', models.FloatField()),
                ('L01', models.CharField(max_length=32)),
                ('L02', models.CharField(max_length=32)),
                ('L03', models.CharField(max_length=32)),
                ('M01', models.CharField(max_length=32)),
                ('M02', models.CharField(max_length=32)),
                ('M03', models.CharField(max_length=32)),
                ('H01', models.CharField(max_length=32)),
                ('H02', models.CharField(max_length=32)),
                ('H03', models.CharField(max_length=32)),
                ('reportinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportInfo')),
            ],
        ),
    ]
