# Generated by Django 3.2.8 on 2022-02-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0175_auto_20220114_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referenceintervalgeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=32, verbose_name='验证指标')),
                ('general', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.general', verbose_name='方法学报告性能验证指标')),
            ],
            options={
                'verbose_name': '参考区间',
                'verbose_name_plural': '参考区间',
            },
        ),
        migrations.AlterField(
            model_name='stabilitygeneraltexts',
            name='stabilitygeneral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.stabilitygeneral', verbose_name=''),
        ),
        migrations.CreateModel(
            name='Referenceintervalgeneraltexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='描述性内容')),
                ('referenceintervalgeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.referenceintervalgeneral', verbose_name='')),
            ],
            options={
                'verbose_name': '描述性内容',
                'verbose_name_plural': '描述性内容',
            },
        ),
        migrations.CreateModel(
            name='Reference_Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.CharField(max_length=32)),
                ('Experimentnum', models.CharField(max_length=32)),
                ('Result', models.CharField(max_length=32)),
                ('reportinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportinfo')),
            ],
        ),
    ]
