# Generated by Django 3.2.8 on 2022-02-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0179_stabilityspecial_stabilityspecialmethod_stabilityspecialtexts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stabilityspecial',
            name='name',
            field=models.CharField(blank=True, default='样品处理后稳定性', editable=False, max_length=32, verbose_name='验证指标'),
        ),
    ]
