# Generated by Django 3.2.8 on 2022-02-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0182_matrixeffect_testspecial_matrixeffect_testspecialmethod_matrixeffect_testspecialtexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrixeffect_testspecialmethod',
            name='matrixeffect_testspecial',
        ),
        migrations.RemoveField(
            model_name='matrixeffect_testspecialtexts',
            name='matrixeffect_testspecial',
        ),
        migrations.DeleteModel(
            name='Matrixeffect_testspecial',
        ),
        migrations.DeleteModel(
            name='Matrixeffect_testspecialmethod',
        ),
        migrations.DeleteModel(
            name='Matrixeffect_testspecialtexts',
        ),
    ]
