# Generated by Django 3.2.8 on 2022-03-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0185_auto_20220321_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTspecialBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Boolean', models.BooleanField(blank=True, null=True, verbose_name='结果不通过时是否关联数据进入报告')),
                ('pTspecial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ptspecial', verbose_name='PT')),
            ],
        ),
    ]
