# Generated by Django 3.2.8 on 2022-03-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0186_ptspecialboolean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptspecialboolean',
            options={'verbose_name': '数据关联', 'verbose_name_plural': '数据关联'},
        ),
        migrations.AddField(
            model_name='carryover',
            name='systermnum',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ptspecialboolean',
            name='pTspecial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report.ptspecial', verbose_name='PT'),
        ),
    ]
