# Generated by Django 3.2.8 on 2022-03-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0187_auto_20220323_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zp_method',
            name='CollisionV',
        ),
        migrations.RemoveField(
            model_name='zp_method',
            name='ConeV',
        ),
        migrations.RemoveField(
            model_name='zp_method',
            name='Times',
        ),
    ]
