# Generated by Django 3.2.8 on 2022-03-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0188_auto_20220325_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zp_method',
            options={'verbose_name': '质谱方法(首行输入列名)', 'verbose_name_plural': '质谱方法(首行输入列名)'},
        ),
        migrations.AddField(
            model_name='zp_method',
            name='Col4',
            field=models.CharField(blank=True, max_length=200, verbose_name='第4列'),
        ),
        migrations.AddField(
            model_name='zp_method',
            name='Col5',
            field=models.CharField(blank=True, max_length=200, verbose_name='第5列'),
        ),
        migrations.AddField(
            model_name='zp_method',
            name='Col6',
            field=models.CharField(blank=True, max_length=200, verbose_name='第6列'),
        ),
        migrations.AddField(
            model_name='zp_method',
            name='Col7',
            field=models.CharField(blank=True, max_length=200, verbose_name='第7列'),
        ),
        migrations.AddField(
            model_name='zp_method',
            name='Col8',
            field=models.CharField(blank=True, max_length=200, verbose_name='第8列'),
        ),
    ]
