# Generated by Django 3.2.8 on 2022-03-29 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0190_auto_20220328_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textarea', models.CharField(max_length=32)),
                ('reportinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reportinfo')),
            ],
        ),
    ]
