# Generated by Django 3.0.5 on 2022-07-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0193_reagentstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='YX_Method2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, max_length=200, verbose_name='步骤')),
                ('time', models.CharField(blank=True, max_length=200, verbose_name='分析时间(min)')),
                ('Flowrate', models.CharField(blank=True, max_length=200, verbose_name='流速(mL/min)')),
                ('Mobile_phaseA', models.CharField(blank=True, max_length=200, verbose_name='流动相A(水相)')),
                ('Mobile_phaseB', models.CharField(blank=True, max_length=200, verbose_name='流动相B(有机相)')),
                ('testmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Testmethod')),
            ],
            options={
                'verbose_name': '液相方法',
                'verbose_name_plural': '液相方法',
            },
        ),
    ]
