# Generated by Django 3.0.5 on 2022-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0194_yx_method2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yx_method2',
            options={'verbose_name': '液相方法2(双系统仪器填写)', 'verbose_name_plural': '液相方法2(双系统仪器填写)'},
        ),
        migrations.AddField(
            model_name='ptspecialaccept',
            name='loq',
            field=models.FloatField(blank=True, null=True, verbose_name='LOQ'),
        ),
    ]
