# Generated by Django 3.0.5 on 2022-10-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0196_auto_20221028_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '所属检测平台及项目组', 'verbose_name_plural': '所属检测平台及项目组'},
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='status',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
