# Generated by Django 3.0.5 on 2022-12-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0198_auto_20221129_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlog',
            name='reportinfo',
        ),
        migrations.DeleteModel(
            name='ReportFlowChart',
        ),
        migrations.DeleteModel(
            name='ReportLog',
        ),
    ]
