# Generated by Django 3.0.5 on 2022-12-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0201_remove_reportlog_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stability',
            name='namestability',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
