# Generated by Django 3.0.5 on 2023-01-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0202_stability_namestability'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinfo',
            name='Protocol_ID1',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='Protocol_ID2',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
