# Generated by Django 3.0.5 on 2023-02-07 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0203_auto_20230117_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICS_main_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=32)),
                ('systermA', models.CharField(max_length=32)),
                ('systermB', models.CharField(max_length=32)),
                ('previous_testtime', models.CharField(max_length=32)),
                ('englishcode', models.CharField(max_length=32)),
                ('chinesecode', models.CharField(max_length=32)),
                ('compare_goal', models.CharField(max_length=32)),
                ('reagent', models.CharField(max_length=32)),
                ('batch', models.CharField(max_length=32)),
                ('testdate', models.CharField(max_length=32)),
                ('assessdate', models.CharField(max_length=32)),
                ('testname', models.CharField(max_length=32)),
                ('researchname', models.CharField(max_length=32)),
                ('researchdate1', models.CharField(max_length=32)),
                ('director', models.CharField(max_length=32)),
                ('researchdate2', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ICS_parameters_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=32)),
                ('criteria1_range', models.CharField(max_length=32)),
                ('criteria1', models.CharField(max_length=32)),
                ('criteria2_range', models.CharField(max_length=32)),
                ('criteria2', models.CharField(max_length=32)),
                ('level1', models.CharField(max_length=32)),
                ('level2', models.CharField(max_length=32)),
                ('digits', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('LOQ', models.CharField(max_length=32)),
                ('ALE', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ICS_data_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samplename', models.CharField(max_length=32)),
                ('resultA', models.CharField(max_length=32)),
                ('resultB', models.CharField(max_length=32)),
                ('bias', models.CharField(max_length=32)),
                ('img', models.ImageField(null=True, upload_to='ICSimg')),
                ('ics_main_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ICS_main_table')),
            ],
        ),
    ]
