# Generated by Django 3.0.5 on 2023-02-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0204_ics_data_table_ics_main_table_ics_parameters_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ics_data_table',
            name='img',
        ),
        migrations.RemoveField(
            model_name='ics_main_table',
            name='chinesecode',
        ),
        migrations.RemoveField(
            model_name='ics_main_table',
            name='englishcode',
        ),
        migrations.RemoveField(
            model_name='ics_main_table',
            name='previous_testtime',
        ),
        migrations.RemoveField(
            model_name='ics_main_table',
            name='systermA',
        ),
        migrations.RemoveField(
            model_name='ics_main_table',
            name='systermB',
        ),
    ]
