# Generated by Django 3.0.5 on 2023-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0205_auto_20230209_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ics_main_table',
            name='chinese_code',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ics_main_table',
            name='compare',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ics_main_table',
            name='english_code',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ics_main_table',
            name='lastdate',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ics_main_table',
            name='target',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
